
<?xml version="1.0" encoding="UTF-8"?>                                                    
		<!DOCTYPE ListeMeuble [                                                                   
			<!ELEMENT ListeMeuble (Meuble)+>                                                      
				<!ELEMENT Meuble (Elmt*,Notice?)+>                                                
					<!ATTLIST Meuble nom CDATA #IMPLIED>                                          
					<!ATTLIST Meuble ref CDATA #REQUIRED>                                         
					<!ATTLIST Meuble unite (mm|cm|m|i) "mm">                                      
					<!ATTLIST Meuble lng CDATA #REQUIRED>                                         
					<!ATTLIST Meuble lar CDATA #REQUIRED>                                         
					<!ATTLIST Meuble hau CDATA #REQUIRED>                                         
					<!ELEMENT Notice (#PCDATA)>                                                   
					<!ELEMENT Elmt (Materiaux)+>                                                  
						<!ATTLIST Elmt num CDATA #REQUIRED>                                       
						<!ATTLIST Elmt nom CDATA #REQUIRED>                                       
						<!ATTLIST Elmt nb CDATA #IMPLIED>                                         
						<!ATTLIST Elmt unite (mm|cm|m|i) "mm">                                    
						<!ATTLIST Elmt lng CDATA #REQUIRED>                                       
						<!ATTLIST Elmt lar CDATA #REQUIRED>                                       
						<!ATTLIST Elmt hau CDATA #REQUIRED>                                       
						<!ELEMENT Materiaux EMPTY>                                                
							<!ATTLIST Materiaux type (BOIS|COMPENSE|STRATIFIE|FER|                
							BRONZE|VERRE|TISSU|CARTON|VIDE|PLASTIQUE|CAOUTCHOU|BAMBOU) "BOIS">    
							<!ATTLIST Materiaux pc CDATA #REQUIRED>                               
		]>

<ListeMeuble>
	<Meuble nom="table Louis XV" ref="510" unite="mm" lng="160" lar="140"
		hau="70">
		<Elmt nom="plateau" num="1" unite="mm" lng="160" lar="140" hau="55">
			<Materiaux type="BOIS" pc="100" />
		</Elmt>
		<Elmt nom="pieds" num="2" nb="4" unite="mm" lng="55" lar="50"
			hau="50">
			<Materiaux type="BOIS" pc="100" />
		</Elmt>
		<Elmt nom="cheville" num="2" nb="16" unite="mm" lng="20" lar="0.7"
			hau="0.7">
			<Materiaux type="BOIS" pc="100" />
		</Elmt>
		<notice>                                                                          
					<![CDATA[ma notice d'emploi.]]>
		</notice>
	</Meuble>
	<Meuble nom="table Basse Verre" ref="512" unite="mm" lng="120"
		lar="80" hau="40">
		<Elmt nom="plateau" num="1" unite="mm" lng="120" lar="80" hau="40">
			<Materiaux type="VERRE" pc="80" />
		</Elmt>
		<Elmt nom="pieds" num="2" nb="4" unite="mm" lng="40" lar="30"
			hau="30">
			<Materiaux type="BRONZE" pc="20" />
		</Elmt>
	</Meuble>
	<Meuble nom="Geridon" ref="125" unite="mm" lng="120" lar="80"
		hau="40">
		<Elmt nom="plateau" num="1" unite="mm" lng="120" lar="80" hau="40">
			<Materiaux type="VERRE" pc="80" />
		</Elmt>
		<Elmt nom="pieds" num="2" nb="4" unite="mm" lng="40" lar="30"
			hau="30">
			<Materiaux type="BRONZE" pc="20" />
		</Elmt>
	</Meuble>
</ListeMeuble>
