<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE ListeMeuble [
		<!ELEMENT ListeMeuble (Meuble+)>
			<!ELEMENT Meuble (Elmt+, Notice?)>
				<!ATTLIST Meuble nom CDATA #IMPLIED>
				<!ATTLIST Meuble ref CDATA #REQUIRED>
				<!ATTLIST Meuble unite (mm|cm|m|i) "mm">
				<!ATTLIST Meuble lng CDATA #REQUIRED>
				<!ATTLIST Meuble lar CDATA #REQUIRED>
				<!ATTLIST Meuble hau CDATA #REQUIRED>
				<!ELEMENT Elmt (Materiaux+)>
					<!ATTLIST Elmt nom CDATA #IMPLIED>
					<!ATTLIST Elmt num CDATA #REQUIRED>
					<!ATTLIST Elmt unite (mm|cm|m|i) "mm" >
					<!ATTLIST Elmt lng CDATA #REQUIRED>
					<!ATTLIST Elmt lar CDATA #REQUIRED>
					<!ATTLIST Elmt hau CDATA #REQUIRED>
					<!ELEMENT Materiaux (#PCDATA)>
						<!ATTLIST Materiaux type (BOIS|COMPENSE|STRATIFIE|FER|BRONZE|VERRE|TISSU|CARTON|VIDE|PLASTIQUE|CAOUTCHOU|BAMBOU) "BOIS">
						<!ATTLIST Materiaux pc CDATA #REQUIRED>	
				<!ELEMENT Notice (#PCDATA)>
	]>
	
	<ListeMeuble>
		<Meuble ref="001451123333" unite="cm" lng="100" lar="80" hau="150" >
			<Elmt num="12" unite="cm" lng="10" lar="5" hau="5">
				<Materiaux  type="BOIS" pc="100%"/>
			</Elmt>
			<Elmt num="12" unite="cm" lng="10" lar="50" hau="15">
				<Materiaux  type="COMPENSE" pc="100%"/>
			</Elmt>
			<Elmt num="12" unite="cm" lng="15" lar="15" hau="5">
				<Materiaux  type="FER" pc="100%"/>
			</Elmt>
			<Notice>"Monte ton meuble comme tu le sens, ne t'inquiete pas s'il reste des piÃ¨ces"</Notice>
		</Meuble>
	</ListeMeuble>