<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE ListeTerme [
	<!ELEMENT ListeTerme (Terme)* >
		<!ELEMENT Terme (#PCDATA) >
		<!ATTLIST Terme x CDATA #REQUIRED>
		<!ATTLIST Terme y CDATA #REQUIRED>
		<!ATTLIST Terme sens (HORIZONTAL|VERTICAL) #REQUIRED>
	]>
	
<ListeTerme>
	<Terme x='2' y='1' sens='VERTICAL'>
		WAGON2 DANSTON CUL^^ULU
	</Terme>
	<Terme x='1' y='2' sens='HORIZONTAL'>
		WAGON1
	</Terme>
	<Terme y='12' x='2' sens='HORIZONTAL'>
		MOM
	</Terme>
	<Terme x='1' y='2' sens='HORIZONTAL'>
		MAMAN
	</Terme>
</ListeTerme>