<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ListTerme[
	<!ELEMENT ListTerme (Terme*)>
		<!ELEMENT Terme (#PCDATA)> 
			<!ATTLIST Terme x CDATA #REQUIRED>
			<!ATTLIST Terme y CDATA #REQUIRED>
			<!ATTLIST Terme sens (HORIZONTAL|VERTICAL)  #REQUIRED>
]>


<ListTerme>

	<Terme x='2' y='1' sens='VERTICAL'>
		WAGON
	</Terme>
	<Terme x='1' y='2' sens='HORIZONTAL'>
		WAGON
	</Terme>
	<Terme x='1' y='2' sens='HORIZONTAL'>
		WAGON
	</Terme>
	<Terme y='2' sens='HORIZONTAL'>
		WAGON
	</Terme>
	<Terme x="nbg inbrm" sens="HORIZONTAL" y=""></Terme>
	<Terme x="" sens="HORIZONTAL" y="">vtfccfcfucuft</Terme>

</ListTerme>
