<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ListeTerme [
	<!ELEMENT ListTerme (terme*)>
		<!ELEMENT Terme (#PCDATA)> 
			<!ATTLIST Terme x CDATA #REQUIRED>
			<!ATTLIST Terme y CDATA #REQUIRED>
			<!ATTLIST Terme sens (HORIZONTAL|VERTICAL)  #REQUIRED>
]>


<ListeTerme>
	<Terme y='1' x='2'    sens='VERTICAL'>
		WAGONA
	</Terme>
	<Terme x='1' y = '2' sens='HORIZONTAL'>
		WAGONB
	</Terme>
	<TOTO x =    '4' y='5' sens='BONJOUR'>
		COCOC
	</TOTO>
	<Terme      y='1' x='2' sens=     'VERTICAL'>
		WAGOND
	</Terme>
	<Terme y='1' x="2" sens='VERTICAL'>
		WAGONE
	</Terme>
	<TermeAutre y='1' x='2' sens='VERTICAL'>
		WAGONF
	</TermeAutre>
	<Terme x='2' sens='VERTICAL'>
		WAGONG
	</Terme>
	<Terme    y='1' sens='VERTICAL'>
		WAGONH
	</Terme>
	<Terme>
		WAGONI
	</Terme>
	<Terme y='1' x='2'     sens="VERTICAL">
		WAGONJ
		
	</Terme>
	<Terme y='1' x='2'     sens="VERTICAL">
		WAGONK
	</Terme>

	<Terme y='1' x='2'     sens="VERTICAL">WAGONL
	</Terme>
	<Terme y='1' x='2'     sens="VERTICAL">WAGONM</Terme>

	<Terme/>
	<Terme 
		y='1' 
		x='2'     
		sens="VERTICAL">BONJOUR</Terme>
</ListeTerme>