=== phvdd59/ActivFormationParis/ProjectActivFormationParis/src/com/formation/beba/save/meuble.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Commercant [
		<!ELEMENT ListeMeuble     (Meuble*,Notice?)>
			<!ELEMENT Meuble(Elmt)+>
			
			<!ATTLIST Meuble nom CDATA #IMPLIED>
			<!ATTLIST Meuble ref CDATA #REQUIRED>
			<!ATTLIST Meuble unite (m|cm|mm|i) "mm">
			<!ATTLIST Meuble lng CDATA #REQUIRED>
			<!ATTLIST Meuble lar CDATA #REQUIRED>
			<!ATTLIST Meuble hau CDATA #REQUIRED>
			
				<!ELEMENT Elmt (Materiaux)+>
				<!ATTLIST Elmt nom CDATA #IMPLIED>
					<!ATTLIST Elmt num CDATA #REQUIRED>
					<!ATTLIST Elmt unite (m|cm|mm|i) "mm" >
					<!ATTLIST Elmt lng CDATA #REQUIRED>
					<!ATTLIST Elmt lar CDATA #REQUIRED>
					<!ATTLIST Elmt hau CDATA #REQUIRED>
			<!ELEMENT Materiaux EMPTY >
					<!ATTLIST Materiaux  pc CDATA #REQUIRED>
					<!ATTLIST Materiaux type (BOIS|COMPENSE|BRONZE|STRATIFIE|FER|VERRE|TISSU|CARTON|VIDE|PLASTIQUE|CAOUTCHOU|BAMBOU) "BOIS">
		<!ELEMENT  Notice ANY>
			]>

=== phvdd59/ActivFormationParis/ProjectActivFormationParis/src/com/formation/anfr/exo/001451.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ListeMeuble SYSTEM "meuble.dtd">     

<ListeMeuble>
	<Meuble nom='IJFD' ref='001451001' unite='cm' lng='40' lar='20'
		hau='10'>
		<Elmt nom='Pied' num='4' unite='cm' lng='10' lar='2' hau='1'>
			<Materiaux pc='100' type='FER'></Materiaux>
		</Elmt>
		<Elmt nom='Base' num='1' unite='cm' lng='40' lar='20' hau='8'>
			<Materiaux pc='20' type='FER'></Materiaux>
			<Materiaux pc='60' type='BRONZE'></Materiaux>
			<Materiaux pc='20'></Materiaux>
		</Elmt>
		<Notice>
			Ceci est une Notice!
		</Notice>
	</Meuble>
	<Meuble nom='BOLFDNU' ref='001451002' unite='i' lng='102' lar='89'
		hau='7'>
		<Elmt nom='sljak' num='1' unite='cm' lng='25' lar='8' hau='14'>
			<Materiaux pc='63' type='STRATIFIE'></Materiaux>
			<Materiaux pc='27' type='TISSU'></Materiaux>
			<Materiaux pc='10' type='PLASTIQUE'></Materiaux>
		</Elmt>
		<Elmt nom='VKLA' num='2' unite='m' lng='1' lar='0.4' hau='0.01'>
			<Materiaux pc='100' type='VIDE'></Materiaux>
		</Elmt>
	</Meuble>
	<Meuble nom='BLOK' ref='001451015' lng='2500' lar='1587' hau='13650'>
		<Elmt nom='KOLBBLOK' num='1' unite='cm' lng='250' lar='1587' hau='1365'>
			<Materiaux pc='100' type='CARTON'></Materiaux>
		</Elmt>
		<Notice>
			De grandes bandes de Carton. eùoµ
			RLGJ ET
			4
			%REG?JEG
			Z .3TKIZ
			H32+5£KZB DTYA934
			6.EV TZAE3¨£T
			51VKFR3ENUEY494%F.?S FHJZEL
		</Notice>
	</Meuble>
</ListeMeuble>
